/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BRouteImport } from './routes/b'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckoutVipRouteImport } from './routes/checkout-vip'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ThankYouVipRouteImport } from './routes/thank-you-vip'
import { Route as UpsellCallRouteImport } from './routes/upsell-call'
import { Route as UpsellStoryIdentityRouteImport } from './routes/upsell-story-identity'
import { Route as UpsellStoryIdentity2RouteImport } from './routes/upsell-story-identity-2'
import { Route as VipRouteImport } from './routes/vip'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BRoute = BRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutVipRoute = CheckoutVipRouteImport.update({
  id: '/checkout-vip',
  path: '/checkout-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouVipRoute = ThankYouVipRouteImport.update({
  id: '/thank-you-vip',
  path: '/thank-you-vip',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellCallRoute = UpsellCallRouteImport.update({
  id: '/upsell-call',
  path: '/upsell-call',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellStoryIdentityRoute = UpsellStoryIdentityRouteImport.update({
  id: '/upsell-story-identity',
  path: '/upsell-story-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellStoryIdentity2Route = UpsellStoryIdentity2RouteImport.update({
  id: '/upsell-story-identity-2',
  path: '/upsell-story-identity-2',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-vip': typeof CheckoutVipRoute
  '/thank-you': typeof ThankYouRoute
  '/thank-you-vip': typeof ThankYouVipRoute
  '/upsell-call': typeof UpsellCallRoute
  '/upsell-story-identity': typeof UpsellStoryIdentityRoute
  '/upsell-story-identity-2': typeof UpsellStoryIdentity2Route
  '/vip': typeof VipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-vip': typeof CheckoutVipRoute
  '/thank-you': typeof ThankYouRoute
  '/thank-you-vip': typeof ThankYouVipRoute
  '/upsell-call': typeof UpsellCallRoute
  '/upsell-story-identity': typeof UpsellStoryIdentityRoute
  '/upsell-story-identity-2': typeof UpsellStoryIdentity2Route
  '/vip': typeof VipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/b': typeof BRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-vip': typeof CheckoutVipRoute
  '/thank-you': typeof ThankYouRoute
  '/thank-you-vip': typeof ThankYouVipRoute
  '/upsell-call': typeof UpsellCallRoute
  '/upsell-story-identity': typeof UpsellStoryIdentityRoute
  '/upsell-story-identity-2': typeof UpsellStoryIdentity2Route
  '/vip': typeof VipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/b'
    | '/checkout'
    | '/checkout-vip'
    | '/thank-you'
    | '/thank-you-vip'
    | '/upsell-call'
    | '/upsell-story-identity'
    | '/upsell-story-identity-2'
    | '/vip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/b'
    | '/checkout'
    | '/checkout-vip'
    | '/thank-you'
    | '/thank-you-vip'
    | '/upsell-call'
    | '/upsell-story-identity'
    | '/upsell-story-identity-2'
    | '/vip'
  id:
    | '__root__'
    | '/'
    | '/b'
    | '/checkout'
    | '/checkout-vip'
    | '/thank-you'
    | '/thank-you-vip'
    | '/upsell-call'
    | '/upsell-story-identity'
    | '/upsell-story-identity-2'
    | '/vip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BRoute: typeof BRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutVipRoute: typeof CheckoutVipRoute
  ThankYouRoute: typeof ThankYouRoute
  ThankYouVipRoute: typeof ThankYouVipRoute
  UpsellCallRoute: typeof UpsellCallRoute
  UpsellStoryIdentityRoute: typeof UpsellStoryIdentityRoute
  UpsellStoryIdentity2Route: typeof UpsellStoryIdentity2Route
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-vip': {
      id: '/checkout-vip'
      path: '/checkout-vip'
      fullPath: '/checkout-vip'
      preLoaderRoute: typeof CheckoutVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-vip': {
      id: '/thank-you-vip'
      path: '/thank-you-vip'
      fullPath: '/thank-you-vip'
      preLoaderRoute: typeof ThankYouVipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-call': {
      id: '/upsell-call'
      path: '/upsell-call'
      fullPath: '/upsell-call'
      preLoaderRoute: typeof UpsellCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-story-identity': {
      id: '/upsell-story-identity'
      path: '/upsell-story-identity'
      fullPath: '/upsell-story-identity'
      preLoaderRoute: typeof UpsellStoryIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upsell-story-identity-2': {
      id: '/upsell-story-identity-2'
      path: '/upsell-story-identity-2'
      fullPath: '/upsell-story-identity-2'
      preLoaderRoute: typeof UpsellStoryIdentity2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BRoute: BRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutVipRoute: CheckoutVipRoute,
  ThankYouRoute: ThankYouRoute,
  ThankYouVipRoute: ThankYouVipRoute,
  UpsellCallRoute: UpsellCallRoute,
  UpsellStoryIdentityRoute: UpsellStoryIdentityRoute,
  UpsellStoryIdentity2Route: UpsellStoryIdentity2Route,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
